# this file is managed by dry-rb/devtools project

name: release

on:
  create:

jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags')
    env:
      GITHUB_LOGIN: dry-bot
      GITHUB_TOKEN: ${{secrets.GH_PAT}}
      GEM_HOST_API_KEY: ${{secrets.GEM_HOST_API_KEY}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: 2.6
      - name: Install dependencies
        run: |
          gem install gem-release
      - name: Set up gem credentials
        run: |
          mkdir -p ~/.gem
          cat ":rubygems_api_key: $GEM_HOST_API_KEY" > ~/.gem/credentials
      - name: Publish to Rubygems
        run: |
          gem release
